# Generated by Django 3.2.7 on 2022-12-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_distance_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='first',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='main.user'),
        ),
    ]
